### ISSUE TITLE
App Crashes when clicking on finish button in PDF signing screen if internet connection breaks. 

### ISSUE THREAD

**Issue by meeramanesh** [docusign/mobile-android-sdk#34]
java.lang.IllegalStateException: Fragment GenericConfirmationDialogFragment{3ac417f} (7282a852-5f28-448a-b27a-bcdaab4b4aaf) not attached to an activity.

        at androidx.fragment.app.Fragment.requireActivity(Fragment.java:928)

        at com.docusign.androidsdk.ui.fragments.GenericConfirmationDialogFragment.onCreateDialog$lambda-16(GenericConfirmationDialogFragment.kt:131)

        at com.docusign.androidsdk.ui.fragments.GenericConfirmationDialogFragment.$r8$lambda$OU2nyw5q4RjcytJX6TWFBquljuU(Unknown Source:0)

        at com.docusign.androidsdk.ui.fragments.GenericConfirmationDialogFragment$$ExternalSyntheticLambda5.onShow(Unknown Source:6)

        at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1747)

        at android.os.Handler.dispatchMessage(Handler.java:106)

        at android.os.Looper.loop(Looper.java:246)

        at android.app.ActivityThread.main(ActivityThread.java:8633)

        at java.lang.reflect.Method.invoke(Native Method)

        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)

        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

2022-04-13 11:02:43.492 28975-28975/com.investcorp.wealth E/DocuSign_DSMTelemetryDelegate: Fragment GenericConfirmationDialogFragment{3ac417f} (7282a852-5f28-448a-b27a-bcdaab4b4aaf) not attached to an activity.

**Comment by naveentds** [comment]
Hi @meeramanesh 
This will be fixed in our next SDK release v1.5.5.

Thanks.

**Comment by naveentds** [comment]
Hi @meeramanesh 
This issue is fixed in SDK v.1.5.5. Please try our latest SDK and let us know how it goes.

Thanks
