### ISSUE TITLE
SDK 1.8.1 - Error while syncing already signed document

### ISSUE THREAD

**Issue by meeramanesh** [docusign/mobile-android-sdk#43]
Good Day!

I have found a rare scenario that when I tried to sync an already signed document, I am getting the below error.
Android Platform is doing online signing.
Could you please check and let me know what this below error referring to?

`syncEnvelope::onError
                                                                                                    com.docusign.androidsdk.exceptions.DSSyncException: Unable to sync offline signed envelope. Envelope is in neither Sync Pending nor Sync Failed status
                                                                                                    	at com.docusign.androidsdk.delegates.DSEnvelopeDelegate$syncEnvelope$1.onComplete(DSEnvelopeDelegate.kt:618)
                                                                                                    	at com.docusign.androidsdk.delegates.DSEnvelopeDelegate.getCachedEnvelope$lambda-8(DSEnvelopeDelegate.kt:261)
                                                                                                    	at com.docusign.androidsdk.delegates.DSEnvelopeDelegate.$r8$lambda$IkFA4poKSF4Ugw7aL5h_HCCzpL0(Unknown Source:0)
                                                                                                    	at com.docusign.androidsdk.delegates.DSEnvelopeDelegate$$ExternalSyntheticLambda18.accept(Unknown Source:6)
                                                                                                    	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
                                                                                                    	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
                                                                                                    	`

**Comment by cbsdsdevsup** [comment]
Hi Meeramanesh,

Thank you for contacting DocuSign Developer Support.

Could you please share:

1. Some example envelopeIDs that produce this error message.
2. The SDK and language (C#, Python etc.) you are using to code.

In the meantime, here is a guide on "How to sync offline signed envelopes" you might find helpful:

Link: https://developers.docusign.com/docs/mobile-sdks/ios-sdk/how-to/sync-offline/

Let us know if you need anything else.

Best regards,
Conar | DocuSign Developer Support

**Comment by meeramanesh** [comment]
Some example envelopeIDs that produce this error message.  ---> b62eb8a0-b43a-4e9e-b003-bcaec4fad4ba
The SDK and language (C#, Python etc.) you are using to code. ---> Android SDK 1.8.1. The issue persists in 1.7.8 also

**Comment by naveentds** [comment]
Hi @meeramanesh 
If you are using online signing API, no need to invoke sync api. The signed document will be synced automatically.
If you are using offline signing API, then only you need to invoke sync API to sync the signed document.

**Comment by meeramanesh** [comment]
Hi @naveentds 
I have a flow like we are just syncing the document. We are not opening the document to sign. I have the template id, then we will create the envelop and try to sync.

This is working fine in one of our environment, its failing in another

The same implementation we are following from past few months which doesn't have any issue. Even in production also same is there.

Could you please guide me if there are any settings from Docusign portal that we should allow sync without downloading teh template?

Thanks in Advance,
Meera Manesh

**Comment by cbsdsdevsup** [comment]
Hi @meeramanesh,

- The error message in your initial message "Unable to sync offline signed envelope. Envelope is in neither Sync Pending nor Sync Failed status" suggests that envelope was synced automatically.
- Perhaps the the device was online during the signing session.
- We would recommend you run an envelope status check before you sync to avoid clashes in the future.

Here is a Guide on "Offline Signing for Mobile":

https://support.docusign.com/s/document-item?language=en_US&rsc_301=&bundleId=gub1579795684748&topicId=oca1579795665127.html&_LANG=enus

If the problem presists please open a case using:

https://support.docusign.com

Best regards,
Conar | DocuSign Developer Support

**Comment by meeramanesh** [comment]
The comments  are not referring the scenario that I have explained. 
I have raised a case in https://support.docusign.com/ .
we will follow up from there.

**Comment by naveentds** [comment]
Hi @meeramanesh, when you create the envelope, try setting 
```
envelope.syncStatus == SyncStatus.PENDING
```
 and see if the issue got resolved.

**Comment by meeramanesh** [comment]
Thanks @naveentds  Its working fine with the provide code change.
